name: Process collection

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo content
      - name: checkout repo content
        uses: actions/checkout@v3

      # Setup Python
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.13

      # Install requirements
      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run
      - name: Run merge.py
        id: run-merge
        run: |
          python merge.py

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}